### ISSUE TITLE
Consider using devDependencies

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solid-auth-client#10]
A lot of the current `dependencies` are actually `devDependencies`, so they are unnecessarily installed when using `npm install solid-auth-client`.

**Comment by RubenVerborgh** [comment]
I don't know where I got that, this seems fine.

**Comment by RubenVerborgh** [comment]
Actually, @dmitrizagidulin remarked that bootstrap might be in the wrong place.

**Comment by dan-f** [comment]
You're right, looks like bootstrap is in the wrong place. Other than that, which are the particular dependencies you believe to be incorrectly categorized?

**Comment by RubenVerborgh** [comment]
Just bootstrap, the others I saw were transitive dependencies from bootstrap I presume.

**Comment by dan-f** [comment]
The other dependencies are `@trust/oidc-rp`, `auth-header`, and `isomorphic-fetch`, which don't relate to bootstrap. I can move bootstrap to the devDependencies, as it's just used in the demo app.

**Comment by RubenVerborgh** [comment]
Works for me!

**Comment by dan-f** [comment]
Great, PR coming shortly.
