### ISSUE TITLE
README Logging in snippet should include the key "popupUri"

### ISSUE THREAD

**Issue by dprat0821** [solid/solid-auth-client#100]
In the **Logging in** session of README.md, there is a snippet of _popupLogin_ with the following statement:
`session = await solid.auth.popupLogin({ popupUri });`
Got blank popup page with it. After checking the source code I tried and found that it should be 
`session = await solid.auth.popupLogin({ popupUri: popupUri });`

My envrionment: MacOS, Angular 7.0.4, Node: 8.12.9. OSX 10.14.2.

**Comment by RubenVerborgh** [comment]
Given that

```
{ popupUri }
```

is syntactic sugar for

```
{ popupUri: popupUri }
```

I strongly suspect the error is somewhere else. Can you verify>

**Comment by RubenVerborgh** [comment]
Happy to hear it works 🙂
