### ISSUE TITLE
Explain details of fetch function

### ISSUE THREAD

**Issue by pheyvaer** [solid/solid-auth-client#101]
The readme states `The fetch method mimics the browser's fetch API.` Does this mean that the input and output are exactly the same as the browser's fetch API?

**Comment by RubenVerborgh** [comment]
Indeed, that is what we are aiming for.

Did you find inconsistencies? Or should we document/explain this better?

**Comment by pheyvaer** [comment]
No inconsistencies. It's about the documentation: I would clearly state that the goal is to have the same input/output.

**Comment by pheyvaer** [comment]
If you want I can add an extra sentence to the documentation via a PR. Let me know 😄

**Comment by RubenVerborgh** [comment]
Yes please!
