### ISSUE TITLE
prepend Numerical ID , the url of the real created file ?

### ISSUE THREAD

**Issue by scenaristeur** [solid/solid-auth-client#104]
the https://github.com/jeff-zucker/solid-file-client/ uses the  solid.auth.fetch(url,request). 

```
createFile(URL,contentType)

fileClient.createFile(newFile).then(success => {
  console.log(`Created file ${newFile}.`);
}, err => console.log(err) );

This method creates a new empty file. The contentType should be specified either in the URL's extension or in the contentType parameter, but not both.

NOTE : if the file already exists, the solid.community server (and others) will create an additional file with a prepended numerical ID 

``` 

https://github.com/jeff-zucker/solid-file-client/issues/8 

So is it possible to retrieve that prepend Numerical ID , the url of the real created file ?

**Comment by scenaristeur** [comment]
yes , it sounds good, the real url could be retrieved with 
var location = response.headers.get('location')
var file = location.substr(location.lastIndexOf('/') + 1)
var url = parentFolder+file;

**Comment by RubenVerborgh** [comment]
> var file = location.substr(location.lastIndexOf('/') + 1)
> var url = parentFolder+file;

That worries me a bit, should probably be:

> url = new URL(location, parentFolder)

**Comment by scenaristeur** [comment]
Txs
