### ISSUE TITLE
Logging in after logging out breaks fetch

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solid-auth-client#11]
When I perform the following steps:
1. `SolidAuthClient.login("https://solidtest.space/")` (and log in with with username / password)
2. `SolidAuthClient.fetch("https://my.solidtest.space/private-resource")`
3. `SolidAuthClient.logout()`
4. `SolidAuthClient.login("https://solidtest.space/")`
5. `SolidAuthClient.fetch("https://my.solidtest.space/private-resource")`

Here, we assume `https://my.solidtest.space/private-resource` triggers a 401.

The following happens:
- In step 2, a 401 is followed by another GET, resulting in 200 (as expected)
- In step 4, I am not redirected to log in, but rather logged in automatically (not fully expected).
- In step 5, the 401 is not followed by another GET

This occurs because, after step 2, solidtest.space sets a cookie which automatically authenticates me in step 4, but does not set an access token.

**Comment by dan-f** [comment]
Hey @RubenVerborgh, thanks for the detailed bug report :)

Could you let me know how you've installed the library / which version you are using? For example, are you on the latest `v0.3.4`?

**Comment by RubenVerborgh** [comment]
Yes, using the latest version, from GitHub.

**Comment by dan-f** [comment]
Just to circle back - I tried reproducing the bug, but I wasn't able to. @RubenVerborgh, feel free to either close this issue or ping me again!

**Comment by RubenVerborgh** [comment]
Bug confirmed with slightly different steps to reproduce. Following up in https://github.com/solid/node-solid-server/issues/523

**Comment by dan-f** [comment]
I'll leave this open until https://github.com/solid/node-solid-server/issues/523 closes.

**Comment by RubenVerborgh** [comment]
Confirmed fixed with https://github.com/solid/node-solid-server/pull/525.
