### ISSUE TITLE
logout() makes undesirable fetch request

### ISSUE THREAD

**Issue by pangolingo** [solid/solid-auth-client#111]
When I call `solid.auth.logout()`, it makes a fetch request to `/.well-known/solid/logout`. When I'm writing frontend-only code (like a demo on Codepen), I'd prefer that this request did not occur. There is no backend set up to handle the request.

Would it be possible to add an option to disable this logout request?

**Comment by RubenVerborgh** [comment]
Ehm, but that is kind of the function of `.logout()` 🙂
Why just not call it?

**Comment by jeff-zucker** [comment]
Is there a spec for what is expected in /.well-known/solid/* files?

**Comment by jeff-zucker** [comment]
Why just not call it? Because being logged in separate windows can mess up logins, it is sometimes necessary to logout() first.

**Comment by RubenVerborgh** [comment]
> Is there a spec for what is expected in /.well-known/solid/* files?

No, but we don't need it at the moment. It's all derived from `/.well-known/openid-configuration` (and the latter does have a spec).

**Comment by RubenVerborgh** [comment]
> it is sometimes necessary to logout() first.

Agreed, but to execute that action, we need to send the request.

**Comment by pangolingo** [comment]
In my use case (building a Solid demo app on Codepen), I expect `logout()` to log me out of the Solid identity provider. And it does, so that's functioning properly. 

It's this expectation of having a local server that threw me off. This doesn't break anything: the `fetch` call is properly wrapped in a try/catch. It just feels odd.

**Comment by jeff-zucker** [comment]
Perhaps indicate in the warning message that it's not an error? Something like"no .well-known was found, so skipped"

**Comment by RubenVerborgh** [comment]
> It's this expectation of having a local server that threw me off. This doesn't break anything: the `fetch` call is properly wrapped in a try/catch. It just feels odd.

I'm not entirely sure what you mean. There is no local server expectation, only an identity provider. What unexpected request happened? (perhaps with full URL?)

**Comment by jeff-zucker** [comment]
It throws some people off to see the message. For example, https://github.com/jeff-zucker/solid-file-client/issues/24 is asking the same question as this issue.

**Comment by RubenVerborgh** [comment]
solid-auth-client doesn't guess that location; it gets it from the server. So https://github.com/jeff-zucker/solid-file-client/issues/24 seems like a misconfigured server.

**Comment by jeff-zucker** [comment]
It can occur with apps run from localhost so missing rather than misconfigured.

**Comment by jeff-zucker** [comment]
Same with the case of codepen - their server isn't misconfigured, it's just not solid-ready.

**Comment by RubenVerborgh** [comment]
Okay, I was confused here. Apparently `/.well-known/solid/logout` _is_ hard-coded on the client (https://github.com/solid/solid-auth-client/blob/v2.3.0/src/webid-oidc.js#L75). I was assuming the server pointed to that location (as it should, because this is a total hack).

**Comment by RubenVerborgh** [comment]
Yeah, upon closer examination, we have no choice but to use that hack with the current OIDC libraries. We could add a warning when it 404s, as @jeff-zucker suggested, but that's the best we have (PR welcome).
