### ISSUE TITLE
Login from local file

### ISSUE THREAD

**Issue by Otto-AA** [solid/solid-auth-client#115]
Is it possible to login from a local website (e.g. file:///path/to/index.html)?

I’ve tried it via the popup (solidAuth.popupLogin({ popupUri: 'https://solid.community/common/popup.html' })), yet this doesn’t work if tested with a file:/// path (localhost and on server do). The errors I get in the console are:
```
Could not deserialize data: undefined popup.html:24:121155
DOMException: “An invalid or illegal string was specified” popup.html:24:121201
```

If I click on a login button in the popup nothing happens.

Is this disabled due to a security concern, or just not implemented/a bug, or am I missing something?

**Comment by RubenVerborgh** [comment]
The browser will not allow that for security reasons.

You need to run that local website through a local web server (i.e., "localhost"), not over the file system.
