### ISSUE TITLE
EventSource support

### ISSUE THREAD

**Issue by boulderwebdev** [solid/solid-auth-client#116]
There should be support for the EventSource API using solid's fetch. This could be accomplished by implementing a polyfill within the solid-auth-client similar to [this library](https://github.com/mattkrick/event-source-polyfill/blob/master/src/EventSourcePolyfill.ts). I imagine this API would look something like

```javascript
const events = solid.EventSource("myapi.example.com/sse/", {withCredentials: true})
events.onmessage = function(e) {
  //...
}
```

**Comment by RubenVerborgh** [comment]
Needs to be tackled on spec level first.

**Comment by elf-pavlik** [comment]
Existing discussion in: https://github.com/solid/solid-spec/issues/123
