### ISSUE TITLE
Can I force authentication?

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solid-auth-client#12]
Now, the library always first needs to encounter 401, creating double the number of requests.
What is the reason for not always sending auth headers when I use the library's `fetch` method?

Can I force sending the auth headers, for instance through options?

**Comment by dan-f** [comment]
>What is the reason for not always sending auth headers when I use the library's fetch method?

That was a design decision to protect user privacy; you don't know ahead of time whether a resource requires authentication, so why expose credentials unnecessarily?

> Can I force sending the auth headers, for instance through options?

I considered this API, but I'm not convinced that it would bring much value, especially since it would require augmenting the `fetch` API.

An alternative solution would be to heuristically cache resources which have required authentication in the past. When making a request, the `fetch` function could check the cache and skip the unauth'd initial request. This would not handle cases in which previously protected resources are made public.

**Comment by RubenVerborgh** [comment]
> That was a design decision to protect user privacy; you don't know ahead of time whether a resource requires authentication, so why expose credentials unnecessarily?

A couple of points to counter that argument:
- The server can always “trick” the client into sending credentials by replying with 401, so if it wants to bypass, it can. In that sense, it's not (adequate) protection.
- If the application uses this library's `fetch` method, instead of regular `fetch`, the application does so because it assumes the resource _can_ be protected.
- (Actually a question, but might become a point depending on the answer.) How much privacy is the client really giving up? What can be achieved with the token on the server side?

> especially since it would require augmenting the `fetch` API.

That does not seem a problem, as long as there is no conflict. For instance, if we pass an extra `requireAuth` or even `requireSolidAuth` to the `options` hash of `fetch`, then it would just be ignored by regular `fetch` anyway. Furthermore, there will be no noticeable behavior from the viewpoint of the calling code (except for better performance).

Importantly, **the server's behavior might be different whether a user is logged in or not, even if there is no 401**. For instance, there might be extra fields included upon authentication. Or the server might return 404 instead of 401 for security purposes. So it is really useful/necessary to be able to force authentication, or even simply have it as default. I.e., we need raw access to the mechanism that triggers after the 401, not only to the wrapper.

So I think we really should consider adding that option, or just sending the auth headers by default. After all, for anything else, we can use regular `fetch`.

**Comment by RubenVerborgh** [comment]
@dan-f I can have a go at this if you like. How would you prefer this to be implemented?

1. Always send 1 request with authentication headers. No option to override.
2. By default, send 1 request with authentication headers. Override with `authenticateFirst: false`.
3. By default, send 1 request without authentication headers, only on 401 send another with authentication. Override with `authenticateFirst: true`.

Seems that 2 is most flexible.

**Comment by dan-f** [comment]
Hey, great points all around!

I also like option 2. I think that it might be worth it to add a `solidAuth` key in the fetch options in case we need to add more options down the road:

```js
import { fetch } from 'solid-auth-client'

fetch('...', { solidAuth: { alwaysProvideCredentials: false /* (true by default) */ } })
```

**Comment by dan-f** [comment]
Thought I'd update this issue after an out-of-band discussion.

Part of the function that the `401` responses perform is to identify their auth protocol using the `www-authenticate` header. If we were to always send the ID token in the initial request we'd be sending credentials to servers that may not necessarily be speaking in WebID-OIDC.

A discussed proposal was to maintain a cache which would associate servers, by host, with the auth protocol (or lack thereof) which they require.
