### ISSUE TITLE
login({ idp:"idp.example.com", username:"you", password:"hmm" })

### ISSUE THREAD

**Issue by linonetwo** [solid/solid-auth-client#122]
Will there be an API likes https://github.com/jeff-zucker/solid-auth-cli#login-idphttpsidpexamplecom-usernameyou-passwordhmm- ?

If I'm going to provide a custom login form and let the user provides that info, will there be any security risk?

It can be used in circumstance likes TiddlyWiki, it's a serverless SPA, can't provide a popup.html by itself.

**Comment by RubenVerborgh** [comment]
> Will there be an API likes [jeff-zucker/solid-auth-cli#login-idphttpsidpexamplecom-usernameyou-passwordhmm-](https://github.com/jeff-zucker/solid-auth-cli#login-idphttpsidpexamplecom-usernameyou-passwordhmm-) ?

I cannot imagine there ever will be. It is entirely up to `idp` to decide how auth goes. Might be username/password, fingerprint, or magic. How IDP does it is not standardized, so we should not assume. Solid CLI is a temporary workaround/hack that is great for now, but not what we want in the future.
