### ISSUE TITLE
Deriving WebID URI from ID Token

### ISSUE THREAD

**Issue by happy-dev** [solid/solid-auth-client#128]
Hi guys, 

Do I understand correctly from [this line](https://github.com/solid/solid-auth-client/blob/186236c5ebaa8b7f474f8f8ab3d38d15c06e101c/src/webid-oidc.js#L54) that only [Method 2 - Value of sub claim contains a valid HTTP(S) URI](https://github.com/solid/webid-oidc-spec#method-2---value-of-sub-claim-contains-a-valid-https-uri) is supported as a way to derive the WebID URI from the ID Token?

**Comment by jaxoncreed** [comment]
For solid-auth-client, yes. Though solid-auth-client is potentially just one of many implementations of a client.

**Comment by happy-dev** [comment]
@jaxoncreed : I know. But it is the one we based our web component on :smile: 
https://git.happy-dev.fr/startinblox/sib-oidc

If we need the other two methods, we will submit a merge request.
We should be good to get started with the `sub` claim. 

Thank you !

**Comment by happy-dev** [comment]
@jaxoncreed : Thinking about it, do you know any other implementation of WebID-OIDC in javascript ?
