### ISSUE TITLE
The problem of "Error: Could not connect to main window." alert message

### ISSUE THREAD

**Issue by peter279k** [solid/solid-auth-client#142]
Hi all developers, I also try to use the solid authentication client to let the Solid App get the access token.

But I also got this alert message. My reproducing issue approaches are as follows:

- Visiting the Solid App.

![image](https://user-images.githubusercontent.com/9021747/68106144-a3463d00-ff1b-11e9-95b4-edaa263554af.png)

I assume that it already has a Pod account then click the "登入" button.

It will present the popup windows and the captured shot are as follows:

![image](https://user-images.githubusercontent.com/9021747/68106269-059f3d80-ff1c-11e9-9568-8dcb2d44572c.png)

(Noticing that the `electric-data-pod.com` domain is my local DNS mapping, and this domain has not registered yet.)

- Then clicking `Log in` button on popup window. And it will present this alert message I mention on this issue title.

![image](https://user-images.githubusercontent.com/9021747/68106377-67f83e00-ff1c-11e9-8607-b02cef2cee1b.png)

- If I change the popup target `https://electric-data-pod.com:8443/popup.html` to the `https://electric-data-pod.com:8443/common/popup.html`, it will be worked.

![image](https://user-images.githubusercontent.com/9021747/68106528-d937f100-ff1c-11e9-8afe-19f0fd2a7ffa.png)

Can anyone explain why this issue happens? Thanks.

**Comment by peter279k** [comment]
Here is the demonstration of Solid client demo.

- Firstly, visiting the following Solid App via `export POPUP_URI='https://electric-data-pod.com:8443/popup.html'; npm run start:demo` command after building the client demo successfully.

![image](https://user-images.githubusercontent.com/9021747/68107951-56fdfb80-ff21-11e9-9b73-abc8e783f097.png)

- Then clicking the `Login via popup` button, it will present following window:

![image](https://user-images.githubusercontent.com/9021747/68108064-b5c37500-ff21-11e9-8097-90d32920b652.png)

- Then clicking `Login in` button, it will present following alert message:

![image](https://user-images.githubusercontent.com/9021747/68108113-d4c20700-ff21-11e9-9c83-83801dc254cc.png)

- If changing into the `export POPUP_URI='https://electric-data-pod.com:8443/common/popup.html'; npm run start:demo` command to run Solid client demo, trying to using same steps.

Then it will present following captured shot:

![image](https://user-images.githubusercontent.com/9021747/68108317-6af62d00-ff22-11e9-85dd-4f0e383dcb3c.png)

**Comment by jaxoncreed** [comment]
Node Solid Server serves the popup from /common/popup.html. Requests to other places will cause problems.

**Comment by peter279k** [comment]
Hi @jaxoncreed, thanks for your passionate explanation.

Closed.
