### ISSUE TITLE
Cannot build NSS from master : following oidc-rp upgrade to 0.10

### ISSUE THREAD

**Issue by bourgeoa** [solid/solid-auth-client#153]
@RubenVerborgh 
https://github.com/solid/node-solid-server/issues/1406 as been flagged as a regression
seems to need adjust code from oidc-rp (solid/solid-cli@8aaf55e)

**Comment by RubenVerborgh** [comment]
It's solid-cli that needs a new version release; this is independent of solid-auth-client.
