### ISSUE TITLE
README confuses starting and building demo/popup

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solid-auth-client#33]
No explicit build instructions given.

**Comment by dan-f** [comment]
Thanks. I'm going to reword "Building the {demo,popup} app" to "Running the {demo,popup} development server", if that sounds good to you.

**Comment by RubenVerborgh** [comment]
Sounds good, but don't we need the building instructions too?

**Comment by dan-f** [comment]
We have build instructions for the popup. Those last two sections are just for acceptance testing the system.

**Comment by RubenVerborgh** [comment]
But `build:popup` doesn't appear in the README?

**Comment by RubenVerborgh** [comment]
…ah, because that script is obsolete now. So maybe remove that script?

**Comment by dan-f** [comment]
That script is not obsolete; I can add it to the README

**Comment by RubenVerborgh** [comment]
No need for me; just wondering what the diff is with the new generation script then?

**Comment by dan-f** [comment]
The new script simply templates the application name into the built popup.

**Comment by RubenVerborgh** [comment]
Okay, fine with me then. No immediate need to have extra docs.
