### ISSUE TITLE
Sync version of currentUser()

### ISSUE THREAD

**Issue by timbl** [solid/solid-auth-client#38]
Hmmm … Looking at a lot of places where me = tabulator.preferemces.get(‘me’) is replaced by me = UI.authn.currentUser() but that last is async, returns a promise. It sems a shame that it has to return a promise — after all it should not do any net access etc
Can we make it sync, or make a sync version?

It should be a quick check and not take any time, so sync should be fine.

The  version below I pit in solid-ui/sigin.js note does not check for expiry of creds

Dmitri Zagidulin @dmitrizagidulin 20:42
i'll take a look. do you mind opening an issue?

Tim Berners-Lee @timbl 20:43
I have made a local one for now
```
/** Checks syncronously whether user is logged in
 *
 * @returns Named Node or null
*/
function currentUser () {
  let str = localStorage['solid-auth-client']
  if (str) {
    let da = JSON.parse(str)
    if (da.session && da.session.webId) {
      // @@ check has not expired
      return $rdf.sym(da.session.webId)
    }
  }
  return null
  // JSON.parse(localStorage['solid-auth-client']).session.webId
}
```

**Comment by RubenVerborgh** [comment]
Might not be necessary anymore with wide async/await support in browsers: https://github.com/RubenVerborgh/solid-yo/commit/1c1d9984fdc8674395f23a58a44ad94ba6f74d33#diff-eacf331f0ffc35d4b482f1d15a887d3bR71

**Comment by RubenVerborgh** [comment]
Not possible in general, since we depend on storage that might be async.
