### ISSUE TITLE
fetch should accept a Request object and relative URLs

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solid-auth-client#41]
Bug identified as part of https://github.com/RubenVerborgh/solid-yo/commit/5e669c828572ae6aba66c8d36573d277bad17c9a#diff-71cdbcc76e910448d35274d715048124R18

**Comment by timbl** [comment]
[offline] I thought fetch() always takes a URI string, while the fetcher functions like load() and nowOrWhenFetched were designed  take an object, but accept a string as well.   Load does p1.uri || p1. The fetch level knows nothing about RDF and so will not take node objects.

**Comment by RubenVerborgh** [comment]
Given that we want a transparent abstraction, our`fetch` should follow the contract of `window.fetch`, which [allows string and `Request` as first parameters](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch).
