### ISSUE TITLE
Error: Cannot issue PoPToken - missing session key

### ISSUE THREAD

**Issue by timbl** [solid/solid-auth-client#50]
alert:

"You don't have, or you couldn't acess, type indexes --lists of things of different types. Create new empty ones? Error: [LTI] Error: (via loadPrefs) Logged in but cannot load profile https://www.w3.org/People/Berners-Lee/card : Error: Fetcher: fetch failed: Error: Cannot issue PoPToken - missing session key

```
(Logged in as https://www.w3.org/People/Berners-Lee/card#i by authentication)
mashlib.js:20158 logIn: Already logged in as https://www.w3.org/People/Berners-Lee/card#i
mashlib.js:51169 Fetcher: https://www.w3.org/People/Berners-Lee/card Non-HTTP fetch error: Error: Cannot issue PoPToken - missing session key
```

**Comment by timbl** [comment]
To reproduce:
- Go to https://timbl.com/timbl/Public/
- Select Home Pane 
- Log in with my w3.org webid

**Comment by RubenVerborgh** [comment]
@timbl Couple of things to check:

- Are we sure that we only have solid-auth-client 2.0.0 in all of the generated mashlib? To test, `cd mashlib; grep solid-auth-client package-lock.json`, and all mentions should have 2.0.0 in them rather than 1.0.x.

- Did you clear localStorage? The storage between 1 and 2 might not be compatible.

**Comment by dmitrizagidulin** [comment]
:+1:, what Ruben said.

**Comment by RubenVerborgh** [comment]
Presumed solved by v2.0.0, feel free to reopen, @timbl.

**Comment by RubenVerborgh** [comment]
Apparently the issue still occurs for @timbl.

**Comment by RubenVerborgh** [comment]
Update from @timbl:

> it seems to be In function issueFor in fetchWithCredentials with resourceServerUri: "https://www.w3.org/People/Berners-Lee/card"
session: {authType: "WebID-TLS", webId: "https://www.w3.org/People/Berners-Lee/card#i", idp: "https://www.w3.org"}
this: ƒ PoPToken()

So the `authType` above is evidence of a solid-auth-client v1.0.0 still running somewhere.

**Comment by RubenVerborgh** [comment]
There are three issues:
- The OIDC library has a state “IDP known, not logged in”, which solid-auth-client interprets as “logged in” in at least one place.
- An incomplete login leaves the state at “IDP known, not logged in”.
- The redirection after a client certificate login is broken, resulting in an incomplete login.

**Comment by RubenVerborgh** [comment]
Fourth issue: https://github.com/solid/node-solid-server/blob/v4.0.15/default-views/auth/login-tls.hbs#L20 actually sets `{ authType: 'WebID-TLS', webId, idp }` in localStorage…

**Comment by RubenVerborgh** [comment]
Following up in https://github.com/solid/node-solid-server/pull/737.
