### ISSUE TITLE
Make app name default to the host

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solid-auth-client#52]
Instead of "Log in to APPNAME", we can just say "Log into example.org".

**Comment by RubenVerborgh** [comment]
Indeed, then we can reuse the popup widely.

**Comment by timbl** [comment]
When we have a single popup.html, then should we install it with NSS in a .well-known place?

.well-known/solid/popup.html

Feed its location to the JS auth logic running in the app in a way which needs less developer configuration by app developers?

**Comment by RubenVerborgh** [comment]
Following up on the .well-known in #53.
