### ISSUE TITLE
Make solid-auth-client work on Safari

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solid-auth-client#55]

**Comment by melvincarvalho** [comment]
Ive used it in the past on mobile successfully.  I will verify again when I get a chance.

**Comment by justinwb** [comment]
Quick bit of extra info - I can reproduce this on desktop safari on macos.

<img width="1439" alt="screen shot 2018-10-18 at 10 35 00 am" src="https://user-images.githubusercontent.com/627228/47162272-a5fad380-d2c1-11e8-83d4-8d10275a8b64.png">

**Comment by RubenVerborgh** [comment]
Yes, confirmed! It works from the home page, but not from the 401.

**Comment by RubenVerborgh** [comment]
So… it is a longstanding Safari bug with 302 redirects: https://bugs.webkit.org/show_bug.cgi?id=158420

https://rubentest.solid.community/ still uses `/common/popup.html` as popup URL, whereas the 401 page uses `/.well-known/solid/login`. The latter 302 redirects to the former, and the browser is supposed to send the hash (containing the OIDC login info) along with that. But it doesn't.

So I will need to remove the redirect from the server, and also fix #54.

**Comment by kjetilk** [comment]
This is fixed, right?

**Comment by RubenVerborgh** [comment]
Yes, #872.
