### ISSUE TITLE
Still used old oidc-rp 0.4.3 instead of solid/oidc-rp

### ISSUE THREAD

**Issue by smalinin** [solid/solid-auth-client#61]

**Comment by smalinin** [comment]
I used https://github.com/solid/solid-auth-client/tree/master 
In file package-lock.json
```
      "@trust/oidc-rp": {
      "version": "0.4.3",
      "resolved": "https://registry.npmjs.org/@trust/oidc-rp/-/oidc-rp-0.4.3.tgz",
      "integrity": "sha512-xIpCLiIfjuVHfoZTlpmKSjBlcVCO9JxaO5oB+8dAd8uJvC0OHf0QyuTHiIO8riYbSyiqSjjBOYNMC9YIC/yAMA==",
      "requires": {
        "@trust/jose": "^0.1.7",
        "@trust/json-document": "^0.1.4",
        "@trust/webcrypto": "0.4.0",
        "base64url": "^2.0.0",
        "node-fetch": "^1.7.2",
        "text-encoding": "^0.6.4",
        "whatwg-url": "^6.1.0"
      }
    },
```
and I have this oidc-rp 0.4.3 package after `npm install` in the `node-modules` folder

**Comment by kjetilk** [comment]
Ah, right.

This depends on https://github.com/solid/oidc-rp/pull/12 and others, I suppose, which @justinwb is working on right now. I think it should be resolved shortly.

**Comment by RubenVerborgh** [comment]
Indeed, I'll go with @justinwb through solid/oidc-rp#12, and then we can tackle this one.

**Comment by RubenVerborgh** [comment]
@smalinin Unfortunately, this is a bigger problem than it seemed, since the API has completely changed from oidc-rp 0.4.3 to 0.7.1. I will need to make some deeper changes.

**Comment by smalinin** [comment]
@RubenVerborgh Ok, but you could create some branch `v_0_4_3` with fixed code in `solid/oidc-rp` repo and use this branch in all solid projects via
```
  "dependencies": {
    "@trust/oidc-rp": "git+https://github.com/solid/oidc-rp.git#v0_4_3",
```
Is it a problem or ?

**Comment by RubenVerborgh** [comment]
@smalinin The upgrade to 0.7.1 should have been successful; you can test in the latest v2.2.1-rc.0.

**Comment by smalinin** [comment]
@RubenVerborgh Checked, the latest solid-auth-client works properly with logout.

**Comment by smalinin** [comment]
@RubenVerborgh The Logout works, but  I forgot to test with Databrowser app (mashlib.js).
If I tried to open Databrowser, I got error "Error: Cannot issue PoPToken - missing id token"

**Comment by RubenVerborgh** [comment]
Yes, the localStorage between different solid-auth-client versions is different.

**Comment by RubenVerborgh** [comment]
Updating the Databrowser version here: https://github.com/linkeddata/mashlib/pull/16
