### ISSUE TITLE
Cannot find module "algorithms/RSASSA-PKCS1-v1_5"

### ISSUE THREAD

**Issue by sentenza** [solid/solid-auth-client#74]
I'm developing an Angular6+ [solid-app](https://github.com/solid/solid-spec#overview) ([codebase](https://github.com/sentenza/ng-solid-material)). The app itself depends on:

    "crypto-js": "^3.1.9-1",
    "rdflib": "^0.19.0",
    "solid-auth-client": "^2.2.6",
    "stream": "0.0.2",
    "webcrypto": "^0.1.1",
    "zone.js": "^0.8.26"

What I'm trying to do is deleting a RDF resource using [`rdflib.UpdateManager.update()`](https://github.com/linkeddata/rdflib.js/blob/fb4b05c945a00f88ee5f8910e2c7c00a3b3ffc8c/src/update-manager.js#L636):

```javascript
    $rdf.UpdateManager(this.store).update(toBeDeleted, [], (uri, ok, message, response) => {
      if (ok) {
        console.log('DELETED')
      } else {
        console.warn(message)
      }
    })
```

You can find more the JSDoc about the `UpdateManager` [here](http://linkeddata.github.io/rdflib.js/doc/UpdateManager.html) and an introduction of rdflib.js [here](https://rawgit.com/linkeddata/rdflib.js/Documentation/Documentation/webapp-intro.html). 

Now, using Firefox `63.0b12 (64-bit)`, I keep getting the following error which I think could be related to the fact that accessing to the *WebCrypto API* [should be restricted to secure origins](https://www.chromium.org/blink/webcrypto) (which is to say `https://` pages). The same error is fired when using Opera. 

    Unhandled Promise rejection: Cannot find module "../algorithms/RSASSA-PKCS1-v1_5". ; Zone: <root> ; Task: Promise.then ; Value: Error: Cannot find module "../algorithms/RSASSA-PKCS1-v1_5".
    at webpackEmptyContext (algorithms sync:2)
    at SupportedAlgorithms.normalize (SupportedAlgorithms.js:84)
    at SubtleCrypto.importKey (SubtleCrypto.js:279)
    at RSASSA_PKCS1_v1_5.importKey (RSASSA-PKCS1-v1_5.js:124)
    at Function.importKey (JWA.js:113)
    at Function.importKey (JWK.js:46)
    at Function.issueFor (PoPToken.js:57)
    at webid-oidc.js:183
    at fetchWithCredentials (authn-fetch.js:63)
    at authn-fetch.js:41 Error: Cannot find module "../algorithms/RSASSA-PKCS1-v1_5".
    at webpackEmptyContext (http://localhost:4200/main.js:11:10)
    at SupportedAlgorithms.normalize (http://localhost:4200/vendor.js:132732:107)
    at SubtleCrypto.importKey (http://localhost:4200/vendor.js:132336:51)
    at RSASSA_PKCS1_v1_5.importKey (http://localhost:4200/vendor.js:124747:28)
    at Function.importKey (http://localhost:4200/vendor.js:125342:34)
    at Function.importKey (http://localhost:4200/vendor.js:125411:18)
    at Function.issueFor (http://localhost:4200/vendor.js:127189:18)
    at http://localhost:4200/vendor.js:185374:44
    at fetchWithCredentials (http://localhost:4200/vendor.js:184423:49)
    at http://localhost:4200/vendor.js:184401:16

I've traced back the issue using the debugger ending up at `webid-oidc.js:183`, and there I stopped because I didn't see anything clearly wrong.

**Am I missing a npm dependency? What is the root cause of this issue?**

**Comment by dmitrizagidulin** [comment]
Hi @sentenza. Are you excluding the `webcrypto` module in your Webpack config? (It and a couple others must be present in the `externals:` section of the config.

**Comment by sentenza** [comment]
> Hi @sentenza. Are you excluding the `webcrypto` module in your Webpack config? (It and a couple others must be present in the `externals:` section of the config.

Do you [this piece of configuration](https://github.com/sentenza/ng-solid-material/blob/3b8635c2e0f56c1dac5728be17171edf1409be84/package.json#L13)?

**Comment by dmitrizagidulin** [comment]
I mean more like this: https://github.com/solid/solid-auth-client/blob/master/webpack/webpack.common.config.js#L23 (I don't think it's equivalent to the section you link to)

**Comment by RubenVerborgh** [comment]
Indeed, @dmitrizagidulin has the correct cause. This piece of code shouldn't be executing in the browser. Instead, the browser should be using the browser's built-in `crypto` instead of `@trust/webcrypto`. With webpack, this can be achieved by using the config linked to above.
