### ISSUE TITLE
bodyUsed consistently false

### ISSUE THREAD

**Issue by rimmartin** [solid/solid-auth-client#78]
Hi,

on fetches of text/plain MIME type the bodyUsed stays false

```
        solid.auth.fetch('https://roger.localhost:8443/public/scad/primary-disk.scad', {
           method: 'GET',
           headers:{
	    'Accept': 'Authorization, Origin, text/*'
	   }
        }).then((result)=>{
          if(result.bodyUsed){
            result.text().then((t)=>{callback(null, t);}).catch((e) => {console.error('Error:', JSON.stringify(e));});
          }
          else {
            callback("No body for "+path, null);
          }
        }).catch((error) => {console.error('Error:', error);});

```

I'm using today's clones of this project and node-solid-server.  Using curl The content I pushed in with this project is returned
```
curl -k --cert ../roger-g74s.cert --key ../roger-g74s.key -I https://roger.localhost:8443/public/scad/primary-disk.scad

```

Is there anything that needs to be set?  Any header?  The same result with
```
solid.auth.fetch('https://roger.localhost:8443/public/scad/primary-disk.scad')
  .then(console.log);
```
bodyUsed is false and get header stuff and ok is true status 200

**Comment by RubenVerborgh** [comment]
This is expected behavior of `window.fetch`, and thus of `solid.auth.fetch`.

[`bodyUsed`}(https://developer.mozilla.org/en-US/docs/Web/API/Body/bodyUsed) indicates whether the body has been read yet, and above, you are not reading it, so it is `false`. You seem to interpret it as a `hasBody` flag, which it is not.

In this example, you will see that it is `false` before you read it, but `true` after you do:

```
let resultCopy;
solid.auth.fetch('https://ruben.verborgh.org/profile/#me', {
  method: 'GET',
  headers: {
    Accept: 'Authorization, Origin, text/*'
  }
}).then(result => {
  resultCopy = result;
  console.log('before reading', resultCopy.bodyUsed);
  return result.text();
}).then(text => {
  console.log('after reading', resultCopy.bodyUsed);
  callback(null, text);
})
.catch(error => console.error('Error:', error));
```
