### ISSUE TITLE
Unable to import solid-auth-client

### ISSUE THREAD

**Issue by james-martin-jd** [solid/solid-auth-client#81]
When attempting to import solid-auth-client (tried many different ways, most recently "import * as solid from 'solid-auth-client'") it is undefined. 

I've been unable to import it into any apps using the es6 style notation. Instead, I've resorted to including the script manually and adding declare let solid; into pages or classes that need to use it.

For applications that aren't using webpack and don't have commonJS, please fix importing so we don't need a workaround.

**Comment by theefer** [comment]
@RubenVerborgh Would you consider refactoring the library to use ES6 modules? You could still use something like Rollup to export bundles in various formats (CommonJS, AMD, UMD), as well as a single-file ES6 bundle which would also enable tree-shaking of unused exports, something that could make a step towards #15.

**Comment by RubenVerborgh** [comment]
> @RubenVerborgh Would you consider refactoring the library to use ES6 modules?

But they are ES6 modules? 😄

**Comment by theefer** [comment]
Doh I must have got confused with rdflib, or somehow the sources in the npm package... My mistake!

Perhaps it might help @james-martin-jd if the npm package also included ES6 modules, rather than CommonJS-transpiled JS? I wonder if this would also enable tree-shaking, by importing sources from the lib folder rather than the dist-lib bundle.

**Comment by megoth** [comment]
> But they are ES6 modules? 😄

Maybe use the "module"-property in package.json? 

- [pkg.module](https://github.com/rollup/rollup/wiki/pkg.module)
- [Setting up multi-platform npm packages](http://2ality.com/2017/04/setting-up-multi-platform-packages.html)
- [A minimal setup for Babel-based npm packages](http://2ality.com/2017/07/npm-packages-via-babel.html)

I think this would enable tree-shaking and the like, as @theefer mentions.

**Comment by RubenVerborgh** [comment]
> Maybe use the "module"-property in package.json?

Ah, I can easily do that, since I already include the src folder with the distribution anyway.

> I think this would enable tree-shaking and the like, as @theefer mentions.

There's not going to be a lot of shaking I think for solid-auth-client, but yes.
