### ISSUE TITLE
Demo does not work with firefox

### ISSUE THREAD

**Issue by y0va** [solid/solid-auth-client#84]
While the demo app works fine with chromium, with firefox just nothing happens when I click on *Log in*. 

In the console I find 

```
[WDS] Disconnected!
solid-auth-client is listening to http://localhost:8081 so ignored a message received from http://localhost:8080.
```

**Comment by RubenVerborgh** [comment]
It does work with Firefox, as this is what I test on, but perhaps we follow slightly different steps. Can you explain step by step what you are doing? Thanks.

**Comment by y0va** [comment]
Sorry,  probably the popup opened in the background. :flushed: 

Works now.

**Comment by RubenVerborgh** [comment]
Awesome 👍
