### ISSUE TITLE
Unable to use login() and logout() when using npm package

### ISSUE THREAD

**Issue by JordanShurmer** [solid/solid-auth-client#85]
I've got a [project set up](https://github.com/JordanShurmer/psop) which loads solid-auth-client as an npm dependency. 

Any call to `logout()` or `login()` fails with a console error saying

```
webid-oidc.js:69 Error finding a WebID-OIDC session
currentSession @ webid-oidc.js:69

webid-oidc.js:70 Error: Cannot find module '../algorithms/RSASSA-PKCS1-v1_5'
    at webpackEmptyContext (algorithms sync:2)
    at SupportedAlgorithms.normalize (SupportedAlgorithms.js:84)
    at SubtleCrypto.importKey (SubtleCrypto.js:279)
    at RSASSA_PKCS1_v1_5.importKey (RSASSA-PKCS1-v1_5.js:124)
    at Function.importKey (JWA.js:113)
    at Function.importKey (JWK.js:46)
    at JWKSet.js:62
    at Array.map (<anonymous>)
    at Function.importKeys (JWKSet.js:61)
    at Function.from (RelyingParty.js:97)
```

If I replace the usage of the npm package with the bundled js at https://solid.github.io/solid-auth-client/dist/solid-auth-client.bundle.js then it works without a problem. You can see this working in the [cdn-solid-auth branch](https://github.com/JordanShurmer/psop/compare/cdn-solid-auth).

**Comment by james-martin-jd** [comment]
I've run into this issue as well. When I manually reference the bundled script in a <script> tag it works fine, but if I import, login throws the same error.

**Comment by RubenVerborgh** [comment]
Your webpack configuration for building your project is not correctly set up. If you are building for the browser, you need to [exclude Node=specific libraries](https://github.com/solid/solid-auth-client/blob/v2.2.10/webpack/webpack.common.config.js#L23-L29).
