### ISSUE TITLE
Don't pre-package libs into browser version

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solid-auth-client#89]
Instead of 3eb6b2dc3eee0ba4644b88a5f4d2e0b701166bb5, we can also do https://github.com/defunctzombie/package-browser-field-spec#replace-specific-files---advanced

**Comment by RubenVerborgh** [comment]
@rubensworks This did not work; I assume because `@trust/webcrypto` is a transitive dependency.

**Comment by rubensworks** [comment]
Hmm, that's too bad.

Perhaps it can be solved by either:
* Add a `browser` entry to `@trust/webcrypto` directly. (This assume we have push-access or can PR to https://github.com/anvilresearch/webcrypto)
* Or, we can create an `isomorphic-webcrypto` wrapper package, similar to [`isomorphic-fetch`](https://www.npmjs.com/package/isomorphic-fetch).

**Comment by RubenVerborgh** [comment]
@rubensworks Very probably; however, we don't want to touch the `@trust` libraries for now. (They seem to have an issue on this though: https://github.com/anvilresearch/webcrypto/issues/57) Maybe I can have a look at getting rid of them altogether in favor of https://www.npmjs.com/package/isomorphic-webcrypto.

**Comment by RubenVerborgh** [comment]
…which turns out to be just https://github.com/kevlened/isomorphic-webcrypto/blob/master/src/index.js

**Comment by rubensworks** [comment]
Oh, so that's exactly what we need then :-)

`isomorphic-webcrypto` seems up-to-date with `@trust/webcrypto`, so it should be low-effort to transition to that.
