### ISSUE TITLE
Make "custom provider" the default option in the popup

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solid-auth-client#93]
…and don't call it "custom".

**Comment by kidehen** [comment]
@RubenVerborgh,

What about "Identity Provider" or "Preferred Identity Provider" rather than "Custom Provider" bearing in mind this is about selecting from which Identity Provider one's credentials are to be authenticated?

**Comment by kidehen** [comment]
@RubenVerborgh,

"Pick Your Identity Provider" or "Pick Your Preferred Identity Provider" since a WebID could verified by a variety of Providers.
