### ISSUE TITLE
Redirection on register only redirects me to solid server

### ISSUE THREAD

**Issue by PulsarFox** [solid/solid-auth-client#98]
On my app I use the .login from OIDCWebClient or solid-auth-client (tried with both)
Then I click on "register" and on success, I expected to be redirected back on my app, but instead I get redirected on the Databrowser on the solid Server. 

How can I be redirected back to my app on register success ?

**Comment by leinue** [comment]
I also encountered this problem. Has this problem been solved?

**Comment by leinue** [comment]
I hope that I can add rediectUrl in solid-auth-client
